name: Build and release

on:
  # Dev
  workflow_dispatch:
  pull_request:
  push:
    # Preview
    branches: [ main ]
    # Stable
    tags: [ "v*" ]
  release:
    types:
      - published

jobs:
  build:
    name: "Build"
    uses: ./.github/workflows/build.yml
    with:
      dotnet_version: '8.0.100'
